### ISSUE TITLE
Instructions on how to setup the presentation

### ISSUE THREAD

**Issue by wilsonmar** [survivejs/how-to-write-a-book-and-survivejs-it#1]
After downloading the zip and expanding it, I get a blank screen when I open index.html.

**Comment by wilsonmar** [comment]
After I issue npm install, I get message:
react-router@1.0.3 requires a peer of history@^1.17.0 but none was installed.

**Comment by bebraw** [comment]
Did you get it to work?

I think I need to replace all the Spectacle bits with a newer version at some point. That will likely resolve the issue.

**Comment by wilsonmar** [comment]
Yes. It works after I installed it correctly. 
If someone verifies the PR containing run instructions, I can close this.

**Comment by bebraw** [comment]
I tried a fresh checkout. Seems to work. Thanks.
